import { useEffect, useState } from 'react'; import { createRoot } from 'react-dom/client'; import './style.css';
const API='/bcman/api'; type Card={id:string;status:string};
function App(){const [data,setData]=useState<any>({users:[],organizations:[],groups:[]});const [user,setUser]=useState('');const [photos,setPhotos]=useState<any[]>([]);const [cards,setCards]=useState<Card[]>([]);const [selected,setSelected]=useState<any>();const [busy,setBusy]=useState('');
 const headers=()=>user?{'X-User-Id':user}:{}; const load=async()=>{const d=await fetch(API+'/bootstrap').then(r=>r.json());setData(d);if(!user)setUser(d.users.find((x:any)=>x.role==='org_admin')?.id||'');if(user)setPhotos(await fetch(API+'/photos',{headers:headers()}).then(r=>r.json()))}; useEffect(()=>{load()},[user]);
 const open=async(p:any)=>{setCards(await fetch(`${API}/photos/${p.id}/cards`,{headers:headers()}).then(r=>r.json()));setSelected(undefined)}; const detail=async(id:string)=>setSelected(await fetch(`${API}/cards/${id}`,{headers:headers()}).then(r=>r.json()));
 const upload=async(e:any)=>{const f=e.target.files?.[0];if(!f)return;setBusy('アップロード中');const fd=new FormData;fd.append('file',f);const r=await fetch(API+'/photos',{method:'POST',headers:headers(),body:fd});const x=await r.json();if(!r.ok)alert(x.detail);else {setBusy('解析を開始しました');await fetch(`${API}/photos/${x.photo_id}/process`,{method:'POST',headers:headers()});setTimeout(()=>{setBusy('');load()},1500)} };
 const save=async()=>{await fetch(`${API}/cards/${selected.id}/contact`,{method:'PUT',headers:{...headers(),'Content-Type':'application/json'},body:JSON.stringify(selected.contact)});alert('保存しました')};
 return <main><header><h1>BCMan</h1><label>利用者 <select value={user} onChange={e=>setUser(e.target.value)}>{data.users.map((u:any)=><option value={u.id}>{u.name} ({u.role})</option>)}</select></label></header><section className="upload"><h2>名刺写真を登録</h2><input type="file" accept="image/jpeg,image/png" capture="environment" onChange={upload}/><p>{busy||'JPEG / PNG、20MBまで。複数名刺を含む写真に対応します。'}</p></section><div className="columns"><section><h2>写真</h2>{photos.map(p=><button className="row" onClick={()=>open(p)}>{p.filename}<small>{p.status}</small></button>)}</section><section><h2>検出名刺</h2>{cards.map(c=><button className="row" onClick={()=>detail(c.id)}>Card <small>{c.status}</small></button>)}</section><section><h2>確認・修正</h2>{selected&&<><img src={API+selected.image_url} /><textarea value={selected.ocr_text||''} readOnly placeholder="OCR結果"/>{Object.entries(selected.contact||{}).filter(([k])=>!['id','card_id','confirmed','created_at','updated_at'].includes(k)).map(([k,v])=><label>{k}<input value={v as string||''} onChange={e=>setSelected({...selected,contact:{...selected.contact,[k]:e.target.value}})}/></label>)}<button onClick={save}>修正を保存</button><button onClick={()=>fetch(`${API}/cards/${selected.id}/confirm`,{method:'POST',headers:headers()}).then(()=>detail(selected.id))}>確定登録</button></>}</section></div></main>}
createRoot(document.getElementById('root')!).render(<App/>);
